[gcp_service_account]
type = "service_account"
project_id = "sidc-464820"
private_key_id = "e48124163d868988712432d46c7b96cb759ca5b9"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC5F61uqaa+pMP4
/5Lt2M3h8P+R4Iix5eJyoTbXx2S1+ixrGNN0HypVaDnqJyr79597d/GK7JAFRuOj
CvIzw1t4sb7UHM+XlbUtv4svHss4ZfM7l0FTKp7ZGr+Yz74dx1xkbs89YC+5kFfw
2D6JYw8yPBKSAzAzcevXHOKbeMM4i+ehLXUBw87lIB7mNviVuH/xDP+4+WVK1x25
iIMUTbCl2KO1RuNMdsOgJvjfCIiqKOxJchNEVR1DUveUcw1TCYOgKdUN9tdDfR5A
rkLycwOSDaUsrs5hAW0invkXTbqE5CmGdNNLkopzfbB2ePSJqc/RM/Pn0x2ayNW3
GIjoCLg3AgMBAAECggEABoIMSWbSWRkGrFD4LpVqmnYp1kw/Ii+DaHpoqOpMN+XQ
Uq0FylXKMZnqPLnHK3gyda9AS/KIwda97ElXPiCxV6tlmqRaBuoZpmkku1xpfYCA
LpPhP8uw2CYLnz42thSrbVCZctQDTugCCj2K6AkWoLKMs0ZEwe+l1jjKyE1VDT42
qhu/mWeIAJqhs7qXyKCCcBnwCwdLU5zrE6/rvunLoSjzOBtpaKr/1OuFA1CmU5lR
ZNdzDSE9VNqpkpeOZh3f26hVZOECNk6C8NA51eNjCin3yZreVdtn0CeteACJS+hh
9J1Z4nck/Z9tz9SPeHvl7ZOdCwN/tQxo4Fl4TlABqQKBgQD1aSvyI0Fh+VrFKKyK
8reHYcXEYuE4dWzEwie+hdjKS6g3KKHQIopr1ANxz3q/HkCCQrw6Z9XWnSNUx5yB
hxyL2XEEI97eilHN/de0l7JyaPYaqWr6msgi2T3oJpXKFA2P1G8rFhJRjTtCP6us
FQnmR3/iYv9SDQk4gtUGhScW/QKBgQDBFDl2JnwMQNYXhlSs5kH9yY+5SOkkeYy1
2TwFdFOC0Owh7JkOajOvPPjpXHgW6kRdV/mp/Snw1hsSrn6rwRUAfmC2Q9nJB0y5
w+l7Mkn2awHrglcgm8b5FoRmL4+KoN3ypVK9FAVf4fRITUaaN3HDFVOkpm3NyfLy
xirF/kTEQwKBgQCpuI6X6yHwrA7Gg5awkaOzkT7AztGLxknu2Ye7D74aSbCQVR1z
YC/y2rF3KFJvknBypcyfZ+hPgGVK4LGwMszfOwYaIuSja22f1Io1byQOU+DAF6LQ
pfL7htp1jxnQo4WtjvFDDwSkOdRdwMLtQ6+Q/qnG20hQaouR9Yl19OhP0QKBgGzB
aph9lvQD9VPs63c0f8lnJpi0U/airLqlsWRVINEXw1pcfd4bvh8gFgjEeDRYIsf9
TPkOS/iHcVp1hY5TRPQxO2KPF3ZfsT0V+EbXjcfKgJtaoJ8Sf+JAZ7VzZsQsVrhd
nRw50ckvajzrojAtuNutAJ9Gy6TV8w4Cx4cc8TknAoGBAKNgQdi54MmvEk28k/Xi
HScdR2mXlLsjR7Ytw9hAhBjgpY/1+LWoSi7O67moQnsGwMWyO998LF0LZr+wgs7d
NYqWaa9cQUR/ey1QFENsu0VY5y4t8Re7mvPYrfOxJjwfREHk3+rqyFk8xv44JUsi
Vcbda2AExEJCWMfxQIErL7oR
-----END PRIVATE KEY-----"""
client_email = "id-025sidc@sidc-464820.iam.gserviceaccount.com"
client_id = "112165191520766743022"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/id-025sidc%40sidc-464820.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
